Improve CrashA detection
MWHunter/Grim pull request #338
Opened 2022-03-06 15:29 UTC by LewUwU

Add check for invalid y position

2022-03-06 17:26 UTC, MWHunter commented
I can't find the hard coded Y in the source code.

2022-03-06 17:29 UTC, MWHunter commented
The only place I remember this value is in Verus's source code: https://github.com/DortDev/Verus-AntiCheat-SourceCode/blob/main/src/me/levansj01/verus/check/checks/crasher/ServerCrasherC.java

2022-03-06 17:30 UTC, LewUwU commented
> The only place I remember this value is in Verus's source code: https://github.com/DortDev/Verus-AntiCheat-SourceCode/blob/main/src/me/levansj01/verus/check/checks/crasher/ServerCrasherC.java

This value is commonly used in anticrash projects

2022-03-07 00:27 UTC, amnoah commented
Theoretically, a player could reach that Y value. This doesn't seem stable.

2022-03-07 08:22 UTC, Jaren8r requested changes

2022-03-07 08:22 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/crash/CrashA.java
> +            if (Math.abs(packet.getPosition().getX()) > HARD_CODED_BORDER || Math.abs(packet.getPosition().getZ()) > HARD_CODED_BORDER || Math.abs(packet.getPosition.getY()) > HARD_CODED_ILLEGAL_Y) {
```suggestion
            if (Math.abs(packet.getPosition().getX()) > HARD_CODED_BORDER || Math.abs(packet.getPosition().getZ()) > HARD_CODED_BORDER || Math.abs(packet.getPosition().getY()) > HARD_CODED_ILLEGAL_Y) {
```

2022-03-08 16:53 UTC, closed without merging