BadPacketsH - Enforce the attack packet order (1.7 - 1.8)
MWHunter/Grim pull request #342
Opened 2022-03-06 19:12 UTC by LewUwU

2022-03-06 23:25 UTC, LewUwU commented
This is a impossible to flag check unless you modify the client

Packet Order is guaranteed due to TCP

2022-03-07 00:31 UTC, amnoah commented
First off, switch statements exist.
Second off, this isn't that great. While yes, it will catch noswing cheats in 1.8 clients only, you could make it compatible for all versions.

If the player has sent an Animation packet, set swung to true. Once they attack, flag is swung is false and then reset swung to false.

This is much simpler, doesn't require you to limit versions, can still catch the cheats, and will perform identically in real scenarios (after the first hit it'll guaranteed catch the cheat. During combat you don't typically start digging so there are no other ways to send Animation).

2022-03-07 08:12 UTC, Jaren8r requested changes
This looks like you tried to copy code from another anti cheat running an older version of PacketEvents without verifying if it compiles correctly.

2022-03-07 08:12 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsH.java
> +import com.github.retrooper.packetevents.wrapper.play.client.WrappedPacketInUseEntity;
WrappedPacketInUseEntity is the class name in PacketEvents 1.8
```suggestion
import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientInteractEntity;
```

2022-03-07 08:12 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsH.java
> +        if (event.getPacketType() == PacketType.Play.Client.USE_ENTITY) {
Should be INTERACT_ENTITY. USE_ENTITY is the property on PacketEvents 1.8
```suggestion
        if (event.getPacketType() == PacketType.Play.Client.INTERACT_ENTITY) {
```

2022-03-07 08:12 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsH.java
> +            WrappedPacketInUseEntity packet = new WrappedPacketInUseEntity(event);
```suggestion
            WrapperPlayClientInteractEntity packet = new WrapperPlayClientInteractEntity(event);
```

2022-03-07 08:12 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsH.java
> +            if (packet.getAction() != WrappedPacketInUseEntity.EntityUseAction.ATTACK) return;
```suggestion
            if (packet.getAction() != WrapperPlayClientInteractEntity.InteractAction.ATTACK) return;
```

2022-03-07 08:12 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsH.java
> +	    if (!swung) flagAndAlert();
Incorrect indentation

2022-03-07 11:32 UTC, Jaren8r requested changes
While the code looks good, this check false positives on newer minecraft versions because the attack is sent before the animation.

2022-03-08 01:35 UTC, LewUwU commented
Tested, this will work only for bad coded cheats like poorly made Criticals in packet mode and etc

2022-03-08 10:24 UTC, Jaren8r approved these changes
Looks good for detecting NoSwing

2022-03-08 16:52 UTC, MWHunter commented
@amnoah is this check valid?

2022-03-08 20:38 UTC, merged

2022-03-09 00:10 UTC, amnoah commented
> 

Yes it should work, although it isn't necessarily the best way possible.