KillAuraA - Multi Aura
MWHunter/Grim pull request #344
Opened 2022-03-07 03:04 UTC by LewUwU

2022-03-07 06:29 UTC, Jaren8r requested changes

2022-03-07 06:29 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +        } else if (WrapperPlayClientPlayerFlying.isFlying(event.getPacket()) {
You're missing an end parenthesis here
```suggestion
        } else if (WrapperPlayClientPlayerFlying.isFlying(event.getPacket())) {
```

2022-03-07 06:29 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +import com.github.retrooper.packetevents.wrapper.play.client.WrappedPacketInUseEntity;
This class doesn't exist

2022-03-07 06:29 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +            ticks = 0;
Using the flying packet to signify the end of a tick isn't reliable on 1.9+ clients as it can be skipped if you don't move.

2022-03-07 06:29 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +package ac.grim.grimac.checks.impl.combat.killaura;
Maybe this should be a badpackets check..?

2022-03-07 10:33 UTC, LewUwU commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +            ticks = 0;
Any suggestion?

2022-03-07 11:01 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +            ticks = 0;
I can't think of any, other than limiting this check to 1.8- clients.

2022-03-07 11:05 UTC, LewUwU commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +            ticks = 0;
I will do that

2022-03-08 10:32 UTC, LewUwU commented on src/main/java/ac/grim/grimac/checks/impl/combat/killaura/KillAuraA.java
> +package ac.grim.grimac.checks.impl.combat.killaura;
Will do

2022-03-08 10:33 UTC, LewUwU commented
I will close this PR to wait the others to be merged or closed

2022-03-08 10:33 UTC, closed without merging