Become less dependent on bukkit
MWHunter/Grim pull request #384
Opened 2022-04-12 09:20 UTC by Jaren8r

Things this pr does:
- Convert fishing from bukkit to packet event

This was a lot harder than I thought it was going to be. I ended up converting the server positions map into a more general server entity map that contains metadata as well as position in order to make this possible.

2022-04-12 18:29 UTC, Jaren8r commented
DeepSource is stupid, these are non-issues.

> Non-null boxed types are inefficient (JAVA-P1000)
`vehicle` *is* nullable (actually I can't find anywhere where it's not-null or even used, maybe it should be removed..?)

> Wrong argument type for Collection remove method (JAVA-E1036)
Probably because serverEntityMap is a map, not a collection. The argument type is correct here.

2022-04-14 17:59 UTC, MWHunter requested changes

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                serverPacketEntity.setMetadata(entityMetadata.getEntityMetadata());
This does not replace all metadata, it just replaces what was set.  That's why I usually parse the metadata to apply to the entity and don't store the metadata directly

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                if (player.entityID != (int) fishingRod.getMetadata().get(0).getValue() - 1) return; // Only send the packet to the person affected
The indexes of the metadata list don't reflect the type of metadata it is.

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +            addEntity(event.getUser(), packetOutEntity.getEntityId(), EntityTypes.PLAYER, packetOutEntity.getPosition(), packetOutEntity.getYaw(), packetOutEntity.getPitch(), 0, packetOutEntity.getEn
0 is fine because minecraft starts at entity ID 1, but other implementations may start at entity ID 0 which could cause issues

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/GrimAPI.java
> +    private JavaPlugin plugin;
I don't see why this is needed.  GrimAC is an instance of JavaPlugin.

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                Vector3f diffF = new Vector3f((float) (diff.getX()*0.1), (float) (diff.getY()*0.1), (float) (diff.getZ()*0.1));
Formatting here is strange, usually there's a space before and after the multiplication sign

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +public class ServerPacketEntity {
I would keep the name TrackerData as the entity tracker is the name for the system that sends the entity positions to the client.  ServerPacketEntity seems more unclear than a name that references the entity tracker.

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +    int data;
This isn't actually used anywhere, and should likely be updated by the metadata field.  hookOwnerEntityId would be more clear than data.

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +    List<EntityData> metadata;
Seems wasteful when we only need the data field

2022-04-14 17:59 UTC, MWHunter commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +            addEntity(event.getUser(), packetOutEntity.getEntityId(), EntityTypes.PLAYER, packetOutEntity.getPosition(), packetOutEntity.getYaw(), packetOutEntity.getPitch(), 0, packetOutEntity.getEn
alternatively make it an Integer and let it be null.

2022-04-14 22:24 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                serverPacketEntity.setMetadata(entityMetadata.getEntityMetadata());
Ah, whoops, will look into

2022-04-14 22:29 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                if (player.entityID != (int) fishingRod.getMetadata().get(0).getValue() - 1) return; // Only send the packet to the person affected
When I was testing, that was the only metadata set on fishing rod so I assumed it was safe, I guess not.

2022-04-14 22:32 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +                Vector3f diffF = new Vector3f((float) (diff.getX()*0.1), (float) (diff.getY()*0.1), (float) (diff.getZ()*0.1));
Fixed

2022-04-14 22:35 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +public class ServerPacketEntity {
Sounds good

2022-04-14 22:45 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/GrimAPI.java
> +    private JavaPlugin plugin;
This isn't *strictly* needed for the normal usage of the plugin, but having the plugin property being an instance of GrimAC prevents other plugins from shading it, and there is no usage of plugin that specifically needs it to be the GrimAC class.
![image](https://user-images.githubusercontent.com/8620569/163489434-0274bb9a-ac1f-4efc-b88c-bbc3a41a8b49.png)

2022-04-14 22:51 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +    int data;
The data field here corresponds to the data field in the spawn entity packet (https://wiki.vg/Protocol#Spawn_Entity / https://wiki.vg/Object_Data), and can have more uses than finding the owner of a fishing hook (although this is all grim uses it for atm).

2022-04-14 22:52 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/utils/data/packetentity/ServerPacketEntity.java
> +    List<EntityData> metadata;
The metadata field is used later to make sure we're only sending the explosion packet to the person that got hooked by the fishing rod, although I'm certainly open to suggestions on an alternate way to store that

2022-04-14 22:58 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java
> +            addEntity(event.getUser(), packetOutEntity.getEntityId(), EntityTypes.PLAYER, packetOutEntity.getPosition(), packetOutEntity.getYaw(), packetOutEntity.getPitch(), 0, packetOutEntity.getEn
I went ahead and made data nullable. I originally didn't do it because the data field was only read for fishing rods and I didn't really care for introducing class overhead, but w/e.

2022-04-15 02:33 UTC, Jaren8r commented
@MWHunter I went ahead and redid how metadata is stored in the TrackerData, and now I am only storing the entity id of the hooked player instead of all of the metadata

2022-04-15 05:06 UTC, Jaren8r commented
Wait a second what the heck did you merge this pr or did github screw up

2022-04-15 05:09 UTC, MWHunter commented
I was trying to merge it

2022-04-15 05:10 UTC, Jaren8r commented
Ah okay, i thought github glitched out because I just resolved merge conflicts as this happened

2022-04-15 05:12 UTC, MWHunter commented
I'll hard push to 2.0 to revert that attempt to merge.

2022-04-15 05:14 UTC, Jaren8r commented
Sounds good, I just got confused by the timing of that

2022-04-16 15:14 UTC, Jaren8r commented
@MWHunter I think it would be best to merge now before my 2.0 and your 2.0 branches get *too* out of sync. I'll likely deal with converting bukkit vectors to packetevents vectors in another pr as that's going to take some time to get right (I did fix the mutable -> immutable change for the current usages in c6bace0 though)

2022-04-18 08:53 UTC, closed without merging

2022-04-25 01:46 UTC, Jaren8r commented
I'm gonna go ahead and make another pr doing this + prs doing the other misc stuff this did, as it became a nightmare from merge conflicts.