Convert bukkit locations to packetevents vectors
MWHunter/Grim pull request #476
Opened 2022-05-08 23:57 UTC by Jaren8r

2022-05-13 22:50 UTC, MWHunter requested changes

2022-05-13 22:50 UTC, MWHunter commented on src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java
> +        Vector3i blockPos = new Vector3i((int) aABB.minX, (int) aABB.minY, (int) aABB.minZ);
blockLocation will round down in negative numbers, while casting to int will round upwards for negative numbers.

2022-05-13 22:50 UTC, MWHunter commented on src/main/java/ac/grim/grimac/manager/SetbackTeleportUtil.java
> -            Pair<Integer, Location> teleportPos = teleports.peek();
PacketEvents has a location variable, I store rotations in case of a future AntiServerLook check

2022-05-14 07:40 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java
> +        Vector3i blockPos = new Vector3i((int) aABB.minX, (int) aABB.minY, (int) aABB.minZ);
Blah, I forgot about negative numbers

2022-05-14 07:42 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/manager/SetbackTeleportUtil.java
> -            Pair<Integer, Location> teleportPos = teleports.peek();
Ah. I saw that it wasn't used, so I assumed it was useless.

2022-05-14 08:26 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/utils/data/SetBackData.java
>      float xRot, yRot;
I almost wonder if I should replace position, xRot and yRot with a single Location field

2022-05-14 08:28 UTC, Jaren8r commented on src/main/java/ac/grim/grimac/manager/SetbackTeleportUtil.java
> -            Pair<Integer, Location> teleportPos = teleports.peek();
I only saw the rotations field used in one instance with % 360 on it, but it was unused, so I assumed it was old / safe to remove. I went ahead and changed the teleports field to store Locations instead of Vector3ds and made it store player.xRot and player.yRot (without % 360). Hopefully this is fine.

2022-06-13 21:32 UTC, closed without merging